<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Models\UpdateRelease.cs" Link="UpdateRelease.cs" />
    <Compile Include="..\Services\PortableUpdate.cs" Link="PortableUpdate.cs" />
  </ItemGroup>
</Project>
